#!/usr/bin/env bash
# Install/upgrade the job-radar skill.
#
# Layout after install:
#   ~/.agents/skills/job-radar/          ← skill source (this folder, rsync'd)
#   ~/.openclaw/skills/job-radar         ← symlink to .agents/skills/job-radar
#   ~/.claude/skills/job-radar           ← symlink to .agents/skills/job-radar
#   ~/.job-radar/                        ← USER DATA (survives skill upgrades)
#     ├── .env                           ← SMTP / LLM credentials
#     ├── profile.yaml                   ← user's matching rules
#     ├── data/radar.sqlite              ← scraped jobs + matches
#     ├── runs/*.json                    ← per-run traces
#     └── logs/radar.log
#
# Idempotent: safe to re-run. Preserves .env / profile.yaml if they exist.
#
# Requires: bash, uv, python3, git, rsync
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"
SKILL_NAME="job-radar"

USER_HOME_DIR="${JOB_RADAR_HOME:-$HOME/.job-radar}"
AGENTS_SKILL_DIR="$HOME/.agents/skills/${SKILL_NAME}"

say() { printf '\033[36m▶\033[0m %s\n' "$1"; }
warn() { printf '\033[33m!\033[0m %s\n' "$1"; }
die() { printf '\033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

# ---------- dependencies ----------
for cmd in uv python3 git rsync; do
  command -v "$cmd" >/dev/null 2>&1 || die "missing dependency: $cmd"
done

# ---------- 1. user data dir ----------
say "preparing user data dir: ${USER_HOME_DIR}"
mkdir -p "${USER_HOME_DIR}"/{data,runs,logs}

if [[ ! -f "${USER_HOME_DIR}/.env" ]]; then
  cp "${REPO_ROOT}/.env.example" "${USER_HOME_DIR}/.env"
  warn "created ${USER_HOME_DIR}/.env — edit it with your SMTP + LLM credentials"
fi

if [[ ! -f "${USER_HOME_DIR}/profile.yaml" ]]; then
  cp "${REPO_ROOT}/profile/example.yaml" "${USER_HOME_DIR}/profile.yaml"
  warn "created ${USER_HOME_DIR}/profile.yaml — edit to customise tracks / keywords"
fi

# Reference helper data (ideal_jds) — always refresh (no secrets)
mkdir -p "${USER_HOME_DIR}/ideal_jds"
rsync -a --delete "${REPO_ROOT}/profile/ideal_jds/" "${USER_HOME_DIR}/ideal_jds/"

# ---------- 2. sync skill source ----------
say "syncing skill source → ${AGENTS_SKILL_DIR}"
mkdir -p "$(dirname "${AGENTS_SKILL_DIR}")"
rsync -a --delete \
  --exclude='.venv' --exclude='__pycache__' --exclude='node_modules' \
  --exclude='data' --exclude='runs' --exclude='logs' \
  --exclude='.env' --exclude='profile/me.yaml' \
  "${REPO_ROOT}/" "${AGENTS_SKILL_DIR}/"

# ---------- 3. install python deps ----------
say "installing python deps with uv (in skill dir) [may take 1-3 min]"
( cd "${AGENTS_SKILL_DIR}" && uv sync --no-progress 2>&1 | tail -5 )

# ---------- 4. symlink to each agent's skills dir ----------
link_skill() {
  local target_dir="$1"
  mkdir -p "${target_dir}"
  local link="${target_dir}/${SKILL_NAME}"
  if [[ -L "$link" ]]; then
    rm -f "$link"
  elif [[ -e "$link" ]]; then
    warn "  ${link} exists and is not a symlink — backing up to ${link}.bak"
    mv "$link" "${link}.bak"
  fi
  ln -s "${AGENTS_SKILL_DIR}" "$link"
  say "  linked ${link} → ${AGENTS_SKILL_DIR}"
}

say "symlinking skill into installed agents"
# Only link for agents that are actually present
for agent_dir in "$HOME/.openclaw/skills" "$HOME/.claude/skills"; do
  parent_dir="$(dirname "$agent_dir")"
  if [[ -d "$parent_dir" ]]; then
    link_skill "$agent_dir"
  fi
done

# ---------- 5. wrapper that injects JOB_RADAR_HOME ----------
say "installing wrapper: /usr/local/bin/job-radar (or ~/.local/bin as fallback)"
WRAPPER_CONTENT=$(cat <<EOF
#!/usr/bin/env bash
# Auto-generated by job-radar install.sh. Do not edit.
export JOB_RADAR_HOME="${USER_HOME_DIR}"
exec uv run --project "${AGENTS_SKILL_DIR}" job-radar "\$@"
EOF
)

install_wrapper() {
  local target="$1"
  if [[ -w "$(dirname "$target")" ]] || [[ $EUID -eq 0 && -d "$(dirname "$target")" ]]; then
    printf '%s\n' "${WRAPPER_CONTENT}" > "$target"
    chmod +x "$target"
    say "  wrapper installed at $target"
    return 0
  fi
  return 1
}

install_wrapper /usr/local/bin/job-radar \
  || { mkdir -p "$HOME/.local/bin" && install_wrapper "$HOME/.local/bin/job-radar"; } \
  || warn "could not install wrapper; run manually: uv run --project ${AGENTS_SKILL_DIR} job-radar"

echo
say "done."
echo
echo "Next steps:"
echo "  1. Edit ${USER_HOME_DIR}/.env (SMTP_USER / SMTP_PASS / SMTP_TO)"
echo "  2. Edit ${USER_HOME_DIR}/profile.yaml if needed"
echo "  3. Run: job-radar test-email"
echo "  4. Run: job-radar run && job-radar digest --daily"
